import { Card, CardActionArea, CardContent, Container, Grid, Typography } from '@mui/material'
import Head from 'next/head'
import Link from 'next/link'

export default function Teacher() {
    return (
        <Container>
            <Head>
                <title>Instructor | Biometric Attendance System</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Typography variant='h3'>Hello Instructor</Typography>
            <Typography variant='h4'>Choose Action</Typography>
            <Grid container>
                <Grid item>
                    <Card sx={{ minWidth: '275px', m: 2, backgroundColor: 'tomato' }}>
                        <Link href={'/home/instructor/view_attendance'}>
                            <CardActionArea>
                                <CardContent>
                                    View Attendance
                                </CardContent>
                            </CardActionArea>
                        </Link>
                    </Card>
                </Grid>
                <Grid item>
                    <Card sx={{ minWidth: '275px', m: 2, backgroundColor: 'dodgerblue' }}>
                        <Link href={'/home/instructor/take_attendance'}>
                            <CardActionArea>
                                <CardContent>
                                    Take Attendance
                                </CardContent>
                            </CardActionArea>
                        </Link>
                    </Card>
                </Grid>
            </Grid>
        </Container>
    )
}