import { Card, CardActionArea, CardContent, Container, Grid, Typography } from '@mui/material'
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Home | Biometric Attendance System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography variant='h3'>Welcome To Biometric Attendance System</Typography>
      <Typography variant='h4'>Login as:</Typography>
      <Grid container>
        <Grid item>
          <Card sx={{minWidth: '275px', m: 2, backgroundColor: 'tomato'}}>
            <Link href={'/home/instructor'}>
              <CardActionArea>
                <CardContent>
                  Instructor
                </CardContent>
              </CardActionArea>
            </Link>
          </Card>
        </Grid>
        <Grid item>
          <Card sx={{minWidth: '275px', m: 2, backgroundColor: 'dodgerblue'}}>
            <Link href={'/home/student'}>
              <CardActionArea>
                <CardContent>
                  Student
                </CardContent>
              </CardActionArea>
            </Link>
          </Card>
        </Grid>
        <Grid item>
          <Card sx={{minWidth: '275px', m: 2, backgroundColor: 'limegreen'}}>
          <Link href={'/home/admin'}>
            <CardActionArea>
              <CardContent>
                Admin
              </CardContent>
            </CardActionArea>
          </Link>
          </Card>
        </Grid>
      </Grid>
    </Container>
  )
}
